#!/usr/bin/env python3
"""
TeachNova 设计模板库生成器（Template Engine v2）

每套模板 = 一套完整的 Design System，而不是一组颜色：
    designSystem  colors / fonts / radius / shadow / spacing / type scale
    ornament      装饰系统（该模板的视觉签名）
    cardStyle     卡片语言（flat / outline / glass / hard / tinted / underline）
    titleStyle    标题语言（rule / bar / boxed / number / underline / center）
    layouts       16 个页面布局组 → 该模板选用的页面母版（每套都不同）
    rhythm        章节节奏 / 背景交替

运行：python3 scripts/gen_ppt_templates.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TPL_DIR = ROOT / "backend" / "tools" / "pptxgenjs" / "templates"

CN_SANS = "PingFang SC"
CN_SERIF = "Songti SC"
CN_KAI = "STKaiti"
CN_HEI = "Heiti SC"


def tpl(
    tid,
    name,
    category,
    description,
    suitable,
    colors,
    fonts,
    ornament,
    card_style,
    title_style,
    layouts,
    radius=None,
    shadow=None,
    spacing=None,
    type_scale=None,
    chart_style=None,
    image_style=None,
    rhythm=None,
    dark=False,
    footer="AI 互动式教学智能体 · TeachNova",
):
    return {
        "id": tid,
        "name": name,
        "version": 2,
        "generation": 2,
        "category": category,
        "description": description,
        "suitable": suitable,
        "tags": suitable[:3],
        "footer": footer,
        "dark": dark,
        "designSystem": {
            "colors": colors,
            "fonts": fonts,
            "radius": radius or {"card": 0.16, "button": 0.3, "image": 0.12, "panel": 0.16},
            "shadow": shadow or {"enabled": False, "opacity": 0.14, "offset": 2, "blur": 8},
            "spacing": spacing or {"margin": 0.72, "gap": 0.3},
            "type": type_scale or {"cover": 42, "section": 36, "head": 28, "sub": 18, "body": 15, "micro": 10, "metric": 40, "quote": 26},
            "ornament": ornament,
            "cardStyle": card_style,
            "titleStyle": title_style,
            "imageStyle": image_style or {"radius": 0.12, "shadow": False, "mask": "soft"},
            "chartStyle": chart_style or {"mode": "light"},
        },
        "layouts": layouts,
        "rhythm": rhythm or {"sectionEvery": 5, "alternateBg": False, "avoidRepeat": True},
    }


TEMPLATES = [
    # ---------------------------------------------------------------- 01
    tpl(
        "fresh-luxury",
        "清新简奢",
        "education",
        "白底、大量留白、细线分割与玻璃质感卡片，柔和渐变，通用教学首选。",
        ["通用教学", "新授课", "教研展示"],
        {
            "background": "F7FAFD",
            "surface": "FFFFFF",
            "surfaceAlt": "EEF4FF",
            "primary": "3B70F6",
            "primarySoft": "DCECFF",
            "accent": "21C2A6",
            "accentSoft": "D9F5EF",
            "text": "172033",
            "muted": "71819A",
            "line": "C8DCF5",
            "onPrimary": "FFFFFF",
            "onAccent": "FFFFFF",
        },
        {"heading": CN_SANS, "body": CN_SANS, "micro": CN_SANS, "headingWeight": "bold"},
        "circle-soft",
        "glass",
        "rule",
        {
            "cover": "cover-classic",
            "agenda": "agenda-list",
            "section": "section-number",
            "content": ["content-lead", "content-sidebar"],
            "cards": ["cards-grid"],
            "case": ["case-brief"],
            "activity": ["activity-steps"],
            "quote": ["quote-left"],
            "metrics": ["metrics-row"],
            "summary": ["summary-map"],
            "ending": ["ending-center"],
            "chart": ["chart-side"],
            "table": ["table-full"],
            "timeline": ["timeline-axis"],
            "process": ["process-chevron"],
            "compare": ["compare-columns"],
        },
        radius={"card": 0.18, "button": 0.32, "image": 0.14},
    ),
    # ---------------------------------------------------------------- 02
    tpl(
        "future-tech",
        "未来科技",
        "tech",
        "深色背景、科技网格、发光线条与巨型数字，数据可视化强，适合理工与 AI 课程。",
        ["AI 课程", "计算机", "科技课件", "项目答辩"],
        {
            "background": "050B18",
            "surface": "0C1729",
            "surfaceAlt": "122444",
            "primary": "00E5FF",
            "primarySoft": "0A3A4A",
            "accent": "7C4DFF",
            "accentSoft": "241A4D",
            "text": "E8F4FF",
            "muted": "7C93B0",
            "line": "1E3category".replace("category", "244"),
            "onPrimary": "041018",
            "onAccent": "FFFFFF",
        },
        {"heading": CN_SANS, "body": CN_SANS, "micro": CN_SANS, "headingWeight": "bold"},
        "glow-grid",
        "glass",
        "bar",
        {
            "cover": "cover-fullbleed",
            "agenda": "agenda-grid",
            "section": "section-full",
            "content": ["content-stack", "content-columns"],
            "cards": ["cards-mosaic"],
            "case": ["case-card"],
            "activity": ["activity-cards"],
            "quote": ["quote-centered"],
            "metrics": ["metrics-hero"],
            "summary": ["summary-board"],
            "ending": ["ending-cta"],
            "chart": ["chart-metric"],
            "table": ["table-split"],
            "timeline": ["timeline-rail"],
            "process": ["process-chevron"],
            "compare": ["compare-split"],
        },
        radius={"card": 0.08, "button": 0.2, "image": 0.06},
        type_scale={"cover": 46, "section": 38, "head": 30, "sub": 18, "body": 15, "micro": 10, "metric": 46, "quote": 28},
        chart_style={"mode": "dark"},
        dark=True,
    ),
    # ---------------------------------------------------------------- 03
    tpl(
        "academic-paper",
        "学术论文",
        "academic",
        "米白纸感、衬线字体、细分割线与脚注式排版，适合论文汇报与学术讲座。",
        ["学术汇报", "论文答辩", "研究方法", "文献综述"],
        {
            "background": "FBF7F0",
            "surface": "FFFFFF",
            "surfaceAlt": "F2EBE0",
            "primary": "7A2E2E",
            "primarySoft": "EFDCD6",
            "accent": "4A5A3A",
            "accentSoft": "DFE5D5",
            "text": "242019",
            "muted": "7C7161",
            "line": "D8CEBE",
            "onPrimary": "FFFFFF",
            "onAccent": "FFFFFF",
        },
        {"heading": CN_SERIF, "body": CN_SERIF, "micro": CN_SANS, "headingWeight": "bold"},
        "paper-edge",
        "underline",
        "underline",
        {
            "cover": "cover-centered",
            "agenda": "agenda-index",
            "section": "section-side",
            "content": ["content-lead", "content-columns"],
            "cards": ["cards-stack"],
            "case": ["case-brief"],
            "activity": ["activity-cards"],
            "quote": ["quote-left"],
            "metrics": ["metrics-grid"],
            "summary": ["summary-map"],
            "ending": ["ending-center"],
            "chart": ["chart-full"],
            "table": ["table-full"],
            "timeline": ["timeline-vertical"],
            "process": ["process-steps"],
            "compare": ["compare-table"],
        },
        radius={"card": 0.04, "button": 0.1, "image": 0.03},
        type_scale={"cover": 40, "section": 34, "head": 27, "sub": 17, "body": 15, "micro": 10, "metric": 36, "quote": 26},
        spacing={"margin": 0.95, "gap": 0.34},
    ),
    # ---------------------------------------------------------------- 04
    tpl(
        "magazine-editorial",
        "杂志编辑",
        "creative",
        "超大标题、不规则排版与大面积图片位，杂志式文字，适合专题与人文课程。",
        ["专题课", "人文社科", "阅读写作", "班会"],
        {
            "background": "FFFFFF",
            "surface": "FFFFFF",
            "surfaceAlt": "F1EFE9",
            "primary": "1A1A1A",
            "primarySoft": "E4E1D8",
            "accent": "E4572E",
            "accentSoft": "FBE3DA",
            "text": "141414",
            "muted": "6E6A62",
            "line": "D6D2C8",
            "onPrimary": "FFFFFF",
            "onAccent": "FFFFFF",
        },
        {"heading": CN_HEI, "body": CN_SANS, "micro": CN_SANS, "headingWeight": "bold"},
        "corner-fold",
        "hard",
        "boxed",
        {
            "cover": "cover-magazine",
            "agenda": "agenda-grid",
            "section": "section-side",
            "content": ["content-columns", "content-stack"],
            "cards": ["cards-mosaic"],
            "case": ["case-card"],
            "activity": ["activity-cards"],
            "quote": ["quote-centered"],
            "metrics": ["metrics-grid"],
            "summary": ["summary-board"],
            "ending": ["ending-center"],
            "chart": ["chart-full"],
            "table": ["table-split"],
            "timeline": ["timeline-rail"],
            "process": ["process-steps"],
            "compare": ["compare-split"],
        },
        radius={"card": 0.02, "button": 0.05, "image": 0.0},
        type_scale={"cover": 54, "section": 40, "head": 32, "sub": 18, "body": 15, "micro": 10, "metric": 44, "quote": 30},
        spacing={"margin": 0.62, "gap": 0.26},
    ),
    # ---------------------------------------------------------------- 05
    tpl(
        "mono-minimal",
        "黑白极简",
        "creative",
        "黑白灰、超大字号、极少装饰，用排版本身制造张力，适合概念讲授。",
        ["概念课", "思辨课", "公开课", "教师培训"],
        {
            "background": "FFFFFF",
            "surface": "FFFFFF",
            "surfaceAlt": "F2F2F2",
            "primary": "111111",
            "primarySoft": "E2E2E2",
            "accent": "8A8A8A",
            "accentSoft": "EDEDED",
            "text": "111111",
            "muted": "8A8A8A",
            "line": "DADADA",
            "onPrimary": "FFFFFF",
            "onAccent": "FFFFFF",
        },
        {"heading": CN_HEI, "body": CN_SANS, "micro": CN_SANS, "headingWeight": "bold"},
        "minimal",
        "outline",
        "center",
        {
            "cover": "cover-centered",
            "agenda": "agenda-index",
            "section": "section-full",
            "content": ["content-lead", "content-stack"],
            "cards": ["cards-row"],
            "case": ["case-brief"],
            "activity": ["activity-steps"],
            "quote": ["quote-centered"],
            "metrics": ["metrics-hero"],
            "summary": ["summary-board"],
            "ending": ["ending-center"],
            "chart": ["chart-full"],
            "table": ["table-full"],
            "timeline": ["timeline-vertical"],
            "process": ["process-steps"],
            "compare": ["compare-split"],
        },
        radius={"card": 0.0, "button": 0.0, "image": 0.0},
        type_scale={"cover": 58, "section": 44, "head": 34, "sub": 20, "body": 16, "micro": 11, "metric": 52, "quote": 32},
        spacing={"margin": 0.9, "gap": 0.4},
    ),
    # ---------------------------------------------------------------- 06
    tpl(
        "keynote-launch",
        "产品发布",
        "tech",
        "深色满版、巨大标题与超大产品图位，极少文字，空间感强，适合成果展示。",
        ["成果汇报", "项目展示", "竞赛答辩", "产品介绍"],
        {
            "background": "000000",
            "surface": "0F0F0F",
            "surfaceAlt": "1C1C1E",
            "primary": "F5F5F7",
            "primarySoft": "2C2C2E",
            "accent": "2997FF",
            "accentSoft": "123A5E",
            "text": "F5F5F7",
            "muted": "8E8E93",
            "line": "2C2C2E",
            "onPrimary": "000000",
            "onAccent": "FFFFFF",
        },
        {"heading": CN_SANS, "body": CN_SANS, "micro": CN_SANS, "headingWeight": "bold"},
        "neon-line",
        "flat",
        "rule",
        {
            "cover": "cover-fullbleed",
            "agenda": "agenda-index",
            "section": "section-full",
            "content": ["content-stack", "content-lead"],
            "cards": ["cards-row"],
            "case": ["case-card"],
            "activity": ["activity-cards"],
            "quote": ["quote-centered"],
            "metrics": ["metrics-hero"],
            "summary": ["summary-board"],
            "ending": ["ending-cta"],
            "chart": ["chart-full"],
            "table": ["table-full"],
            "timeline": ["timeline-rail"],
            "process": ["process-chevron"],
            "compare": ["compare-split"],
        },
        radius={"card": 0.12, "button": 0.3, "image": 0.16},
        type_scale={"cover": 52, "section": 42, "head": 32, "sub": 20, "body": 16, "micro": 11, "metric": 56, "quote": 30},
        chart_style={"mode": "dark"},
        dark=True,
    ),
    # ---------------------------------------------------------------- 07
    tpl(
        "glass-morphism",
        "玻璃拟态",
        "tech",
        "半透明玻璃卡片、柔光渐变与柔和阴影，层次通透，与 TeachNova 品牌调性一致。",
        ["品牌课件", "公开示范课", "教学设计", "教研分享"],
        {
            "background": "EEF2FF",
            "surface": "FFFFFF",
            "surfaceAlt": "E3E9FF",
            "primary": "5B6CFF",
            "primarySoft": "DCE0FF",
            "accent": "FF7AB8",
            "accentSoft": "FFE1EF",
            "text": "1E2340",
            "muted": "737BA0",
            "line": "C9CFF5",
            "onPrimary": "FFFFFF",
            "onAccent": "3A1030",
        },
        {"heading": CN_SANS, "body": CN_SANS, "micro": CN_SANS, "headingWeight": "bold"},
        "glass-orb",
        "glass",
        "boxed",
        {
            "cover": "cover-classic",
            "agenda": "agenda-grid",
            "section": "section-number",
            "content": ["content-sidebar", "content-lead"],
            "cards": ["cards-grid", "cards-row"],
            "case": ["case-brief"],
            "activity": ["activity-cards"],
            "quote": ["quote-left"],
            "metrics": ["metrics-row"],
            "summary": ["summary-map"],
            "ending": ["ending-center"],
            "chart": ["chart-side"],
            "table": ["table-full"],
            "timeline": ["timeline-axis"],
            "process": ["process-chevron"],
            "compare": ["compare-columns"],
        },
        radius={"card": 0.26, "button": 0.4, "image": 0.2},
        shadow={"enabled": True, "opacity": 0.16, "offset": 3, "blur": 12, "color": "2B2F6B"},
        rhythm={"sectionEvery": 5, "alternateBg": True, "avoidRepeat": True},
    ),
    # ---------------------------------------------------------------- 08
    tpl(
        "3d-education",
        "3D 教育",
        "education",
        "立体卡片、悬浮元素与空间层次，配合贴纸式装饰，适合知识点拆解。",
        ["知识点拆解", "重难点突破", "互动课"],
        {
            "background": "F4F7FB",
            "surface": "FFFFFF",
            "surfaceAlt": "E7EEF9",
            "primary": "4C6FFF",
            "primarySoft": "DCE6FF",
            "accent": "FFB020",
            "accentSoft": "FFF0D6",
            "text": "1C2434",
            "muted": "6E7A90",
            "line": "CBD7EC",
            "onPrimary": "FFFFFF",
            "onAccent": "3A2A00",
        },
        {"heading": CN_HEI, "body": CN_SANS, "micro": CN_SANS, "headingWeight": "bold"},
        "sticker",
        "hard",
        "boxed",
        {
            "cover": "cover-split",
            "agenda": "agenda-grid",
            "section": "section-number",
            "content": ["content-columns", "content-sidebar"],
            "cards": ["cards-mosaic", "cards-grid"],
            "case": ["case-card"],
            "activity": ["activity-cards"],
            "quote": ["quote-left"],
            "metrics": ["metrics-grid"],
            "summary": ["summary-board"],
            "ending": ["ending-center"],
            "chart": ["chart-side"],
            "table": ["table-split"],
            "timeline": ["timeline-axis"],
            "process": ["process-chevron"],
            "compare": ["compare-columns"],
        },
        radius={"card": 0.1, "button": 0.34, "image": 0.14},
        shadow={"enabled": True, "opacity": 0.18, "offset": 3, "blur": 10, "color": "1B2A55"},
    ),
    # ---------------------------------------------------------------- 09
    tpl(
        "whiteboard-class",
        "白板课堂",
        "education",
        "手写体、粉笔质感、便利贴与手绘箭头，还原真实课堂板书的临场感。",
        ["日常授课", "习题讲评", "板书重现", "小组探究"],
        {
            "background": "FDFCF8",
            "surface": "FFFFFF",
            "surfaceAlt": "F3F0E7",
            "primary": "2E5EAA",
            "primarySoft": "DEE9F8",
            "accent": "F0A202",
            "accentSoft": "FCEBCB",
            "text": "22303F",
            "muted": "7A8798",
            "line": "DCD8CB",
            "onPrimary": "FFFFFF",
            "onAccent": "3A2A00",
        },
        {"heading": CN_KAI, "body": CN_SANS, "micro": CN_SANS, "headingWeight": "bold"},
        "chalk-doodle",
        "outline",
        "rule",
        {
            "cover": "cover-classic",
            "agenda": "agenda-list",
            "section": "section-number",
            "content": ["content-lead", "content-stack"],
            "cards": ["cards-stack"],
            "case": ["case-brief"],
            "activity": ["activity-steps"],
            "quote": ["quote-left"],
            "metrics": ["metrics-row"],
            "summary": ["summary-map"],
            "ending": ["ending-center"],
            "chart": ["chart-side"],
            "table": ["table-full"],
            "timeline": ["timeline-axis"],
            "process": ["process-steps"],
            "compare": ["compare-columns"],
        },
        radius={"card": 0.08, "button": 0.36, "image": 0.06},
        type_scale={"cover": 44, "section": 36, "head": 29, "sub": 18, "body": 16, "micro": 11, "metric": 40, "quote": 28},
    ),
    # ---------------------------------------------------------------- 10
    tpl(
        "textbook-style",
        "教材风",
        "education",
        "教材版式、知识框、章节编号与重点标记，最贴近中小学课堂的阅读习惯。",
        ["中小学课堂", "同步教学", "单元复习", "考点梳理"],
        {
            "background": "FFFFFF",
            "surface": "FFFFFF",
            "surfaceAlt": "F1F6F4",
            "primary": "1F7A5C",
            "primarySoft": "DCEFE7",
            "accent": "D9534F",
            "accentSoft": "FBE3E2",
            "text": "22303A",
            "muted": "6E7C86",
            "line": "CFE0D9",
            "onPrimary": "FFFFFF",
            "onAccent": "FFFFFF",
        },
        {"heading": CN_HEI, "body": CN_SANS, "micro": CN_SANS, "headingWeight": "bold"},
        "edge-block",
        "tinted",
        "number",
        {
            "cover": "cover-classic",
            "agenda": "agenda-list",
            "section": "section-side",
            "content": ["content-stack", "content-lead"],
            "cards": ["cards-stack"],
            "case": ["case-brief"],
            "activity": ["activity-steps"],
            "quote": ["quote-left"],
            "metrics": ["metrics-row"],
            "summary": ["summary-map"],
            "ending": ["ending-center"],
            "chart": ["chart-side"],
            "table": ["table-full"],
            "timeline": ["timeline-vertical"],
            "process": ["process-steps"],
            "compare": ["compare-table"],
        },
        radius={"card": 0.06, "button": 0.24, "image": 0.06},
        type_scale={"cover": 42, "section": 36, "head": 29, "sub": 18, "body": 16, "micro": 11, "metric": 38, "quote": 26},
    ),
    # ---------------------------------------------------------------- 11
    tpl(
        "business-consulting",
        "商业咨询",
        "business",
        "结论先行、矩阵与流程图，麦肯锡式结构化表达，适合方案汇报与复盘。",
        ["方案汇报", "项目复盘", "教学设计说明", "管理培训"],
        {
            "background": "FFFFFF",
            "surface": "FFFFFF",
            "surfaceAlt": "F4F6F8",
            "primary": "0A2540",
            "primarySoft": "DCE5EE",
            "accent": "E31837",
            "accentSoft": "FBE0E4",
            "text": "152238",
            "muted": "67748A",
            "line": "D3DAE3",
            "onPrimary": "FFFFFF",
            "onAccent": "FFFFFF",
        },
        {"heading": CN_HEI, "body": CN_SANS, "micro": CN_SANS, "headingWeight": "bold"},
        "corner-fold",
        "outline",
        "bar",
        {
            "cover": "cover-magazine",
            "agenda": "agenda-index",
            "section": "section-side",
            "content": ["content-columns", "content-stack"],
            "cards": ["cards-grid"],
            "case": ["case-card"],
            "activity": ["activity-cards"],
            "quote": ["quote-left"],
            "metrics": ["metrics-grid"],
            "summary": ["summary-board"],
            "ending": ["ending-cta"],
            "chart": ["chart-full"],
            "table": ["table-split"],
            "timeline": ["timeline-vertical"],
            "process": ["process-steps"],
            "compare": ["compare-table"],
        },
        radius={"card": 0.03, "button": 0.05, "image": 0.02},
        type_scale={"cover": 46, "section": 38, "head": 30, "sub": 18, "body": 15, "micro": 10, "metric": 42, "quote": 26},
    ),
    # ---------------------------------------------------------------- 12
    tpl(
        "data-dashboard",
        "数据驾驶舱",
        "business",
        "仪表盘式布局、指标卡与趋势图，适合学情分析、成绩分析与教学诊断。",
        ["学情分析", "成绩诊断", "数据复盘", "教育测量"],
        {
            "background": "0B1220",
            "surface": "131C2E",
            "surfaceAlt": "1B2740",
            "primary": "35D0BA",
            "primarySoft": "134038",
            "accent": "FFB020",
            "accentSoft": "453116",
            "text": "E6EDF7",
            "muted": "7F90AA",
            "line": "24314C",
            "onPrimary": "04231E",
            "onAccent": "3A2A00",
        },
        {"heading": CN_HEI, "body": CN_SANS, "micro": CN_SANS, "headingWeight": "bold"},
        "blueprint",
        "tinted",
        "number",
        {
            "cover": "cover-fullbleed",
            "agenda": "agenda-grid",
            "section": "section-full",
            "content": ["content-stack", "content-columns"],
            "cards": ["cards-mosaic"],
            "case": ["case-card"],
            "activity": ["activity-cards"],
            "quote": ["quote-centered"],
            "metrics": ["metrics-grid", "metrics-hero"],
            "summary": ["summary-board"],
            "ending": ["ending-cta"],
            "chart": ["chart-metric", "chart-full"],
            "table": ["table-full"],
            "timeline": ["timeline-rail"],
            "process": ["process-chevron"],
            "compare": ["compare-table"],
        },
        radius={"card": 0.06, "button": 0.16, "image": 0.05},
        type_scale={"cover": 44, "section": 36, "head": 28, "sub": 18, "body": 14, "micro": 10, "metric": 44, "quote": 26},
        chart_style={"mode": "dark"},
        dark=True,
    ),
    # ---------------------------------------------------------------- 13
    tpl(
        "timeline-story",
        "时间轴故事",
        "creative",
        "大年份、有机曲线与图片位，用时间线讲知识的发展脉络。",
        ["历史课", "科学史", "人物传记", "单元导入"],
        {
            "background": "FFFDF7",
            "surface": "FFFFFF",
            "surfaceAlt": "F5EFE6",
            "primary": "B45309",
            "primarySoft": "F6E6CE",
            "accent": "0E7490",
            "accentSoft": "D5EEF3",
            "text": "2B2419",
            "muted": "7C7365",
            "line": "E0D5C3",
            "onPrimary": "FFFFFF",
            "onAccent": "FFFFFF",
        },
        {"heading": CN_SERIF, "body": CN_SANS, "micro": CN_SANS, "headingWeight": "bold"},
        "organic-curve",
        "glass",
        "underline",
        {
            "cover": "cover-split",
            "agenda": "agenda-index",
            "section": "section-side",
            "content": ["content-lead", "content-sidebar"],
            "cards": ["cards-row"],
            "case": ["case-brief"],
            "activity": ["activity-steps"],
            "quote": ["quote-centered"],
            "metrics": ["metrics-row"],
            "summary": ["summary-map"],
            "ending": ["ending-center"],
            "chart": ["chart-side"],
            "table": ["table-full"],
            "timeline": ["timeline-rail", "timeline-vertical"],
            "process": ["process-chevron"],
            "compare": ["compare-columns"],
        },
        radius={"card": 0.2, "button": 0.36, "image": 0.16},
        type_scale={"cover": 44, "section": 38, "head": 29, "sub": 18, "body": 15, "micro": 10, "metric": 42, "quote": 28},
    ),
    # ---------------------------------------------------------------- 14
    tpl(
        "comic-teaching",
        "漫画教学",
        "education",
        "对话框、剧情分镜与贴纸元素，把知识点变成故事，适合低龄与趣味导入。",
        ["趣味导入", "小学课堂", "情景对话", "安全教育"],
        {
            "background": "FFF9F0",
            "surface": "FFFFFF",
            "surfaceAlt": "FFEFD6",
            "primary": "FF6B6B",
            "primarySoft": "FFE0E0",
            "accent": "FFD93D",
            "accentSoft": "FFF5C2",
            "text": "2E2A26",
            "muted": "7C7168",
            "line": "F0DCC0",
            "onPrimary": "FFFFFF",
            "onAccent": "3A3200",
        },
        {"heading": CN_HEI, "body": CN_SANS, "micro": CN_SANS, "headingWeight": "bold"},
        "sticker",
        "hard",
        "boxed",
        {
            "cover": "cover-split",
            "agenda": "agenda-grid",
            "section": "section-number",
            "content": ["content-columns", "content-stack"],
            "cards": ["cards-row"],
            "case": ["case-card"],
            "activity": ["activity-cards"],
            "quote": ["quote-left"],
            "metrics": ["metrics-row"],
            "summary": ["summary-board"],
            "ending": ["ending-center"],
            "chart": ["chart-side"],
            "table": ["table-full"],
            "timeline": ["timeline-axis"],
            "process": ["process-chevron"],
            "compare": ["compare-columns"],
        },
        radius={"card": 0.22, "button": 0.42, "image": 0.18},
        shadow={"enabled": True, "opacity": 0.12, "offset": 3, "blur": 6, "color": "7A4A2A"},
        type_scale={"cover": 46, "section": 36, "head": 30, "sub": 19, "body": 16, "micro": 11, "metric": 40, "quote": 28},
    ),
    # ---------------------------------------------------------------- 15
    tpl(
        "chinese-ink",
        "水墨国学",
        "creative",
        "宣纸底色、水墨留白、印章与书法标题，适合语文、历史与国学课程。",
        ["语文", "历史", "国学", "传统文化"],
        {
            "background": "F5EFE1",
            "surface": "FBF7EE",
            "surfaceAlt": "E9DFC9",
            "primary": "2B2B2B",
            "primarySoft": "DCD3C0",
            "accent": "A2372F",
            "accentSoft": "EFD9D5",
            "text": "26221C",
            "muted": "7A7263",
            "line": "CFC5AE",
            "onPrimary": "F5EFE1",
            "onAccent": "FFFFFF",
        },
        {"heading": CN_KAI, "body": CN_SANS, "micro": CN_SANS, "headingWeight": "bold"},
        "ink-corner",
        "outline",
        "center",
        {
            "cover": "cover-centered",
            "agenda": "agenda-index",
            "section": "section-side",
            "content": ["content-lead", "content-columns"],
            "cards": ["cards-stack"],
            "case": ["case-brief"],
            "activity": ["activity-cards"],
            "quote": ["quote-centered"],
            "metrics": ["metrics-grid"],
            "summary": ["summary-map"],
            "ending": ["ending-center"],
            "chart": ["chart-full"],
            "table": ["table-full"],
            "timeline": ["timeline-vertical"],
            "process": ["process-steps"],
            "compare": ["compare-split"],
        },
        radius={"card": 0.03, "button": 0.06, "image": 0.02},
        spacing={"margin": 0.85, "gap": 0.34},
        type_scale={"cover": 46, "section": 38, "head": 30, "sub": 18, "body": 16, "micro": 11, "metric": 38, "quote": 30},
    ),
    # ---------------------------------------------------------------- 16
    tpl(
        "nature-eco",
        "自然生态",
        "creative",
        "植物纹理、有机曲线与柔和绿色，适合生物、地理与科学探究课。",
        ["生物", "地理", "科学探究", "环境教育"],
        {
            "background": "F3F9F4",
            "surface": "FFFFFF",
            "surfaceAlt": "E3F1E6",
            "primary": "2F7A4F",
            "primarySoft": "D8EEDF",
            "accent": "C98A2E",
            "accentSoft": "F6E9CF",
            "text": "1E2C23",
            "muted": "6E8073",
            "line": "CBE0D0",
            "onPrimary": "FFFFFF",
            "onAccent": "FFFFFF",
        },
        {"heading": CN_SANS, "body": CN_SANS, "micro": CN_SANS, "headingWeight": "bold"},
        "organic-curve",
        "glass",
        "rule",
        {
            "cover": "cover-split",
            "agenda": "agenda-list",
            "section": "section-number",
            "content": ["content-sidebar", "content-lead"],
            "cards": ["cards-row", "cards-grid"],
            "case": ["case-brief"],
            "activity": ["activity-steps"],
            "quote": ["quote-left"],
            "metrics": ["metrics-row"],
            "summary": ["summary-map"],
            "ending": ["ending-center"],
            "chart": ["chart-side"],
            "table": ["table-full"],
            "timeline": ["timeline-axis"],
            "process": ["process-chevron"],
            "compare": ["compare-columns"],
        },
        radius={"card": 0.24, "button": 0.38, "image": 0.2},
        type_scale={"cover": 42, "section": 36, "head": 28, "sub": 18, "body": 15, "micro": 10, "metric": 38, "quote": 26},
    ),
    # ---------------------------------------------------------------- 17
    tpl(
        "kids-class",
        "儿童课堂",
        "education",
        "大色块、超大圆角、贴纸与卡通角色位，适合幼儿与小学低年级。",
        ["幼儿教育", "小学低年级", "绘本阅读", "启蒙课"],
        {
            "background": "FFF7EE",
            "surface": "FFFFFF",
            "surfaceAlt": "FFE9D2",
            "primary": "FF8A3D",
            "primarySoft": "FFE2CC",
            "accent": "34C3A6",
            "accentSoft": "D6F5EE",
            "text": "33291F",
            "muted": "857768",
            "line": "F3D9BE",
            "onPrimary": "FFFFFF",
            "onAccent": "04382F",
        },
        {"heading": CN_HEI, "body": CN_SANS, "micro": CN_SANS, "headingWeight": "bold"},
        "sticker",
        "flat",
        "boxed",
        {
            "cover": "cover-split",
            "agenda": "agenda-grid",
            "section": "section-number",
            "content": ["content-stack", "content-columns"],
            "cards": ["cards-row"],
            "case": ["case-card"],
            "activity": ["activity-cards"],
            "quote": ["quote-left"],
            "metrics": ["metrics-row"],
            "summary": ["summary-board"],
            "ending": ["ending-center"],
            "chart": ["chart-side"],
            "table": ["table-full"],
            "timeline": ["timeline-axis"],
            "process": ["process-chevron"],
            "compare": ["compare-columns"],
        },
        radius={"card": 0.3, "button": 0.5, "image": 0.24},
        shadow={"enabled": True, "opacity": 0.1, "offset": 3, "blur": 6, "color": "8A5A2A"},
        type_scale={"cover": 48, "section": 38, "head": 32, "sub": 20, "body": 17, "micro": 12, "metric": 42, "quote": 28},
    ),
    # ---------------------------------------------------------------- 18
    tpl(
        "thesis-defense",
        "高校答辩",
        "academic",
        "深蓝学术底色、论文结构、研究框架与数据图表，适合毕业与课题答辩。",
        ["毕业答辩", "课题汇报", "研究生课程", "学术竞赛"],
        {
            "background": "FFFFFF",
            "surface": "FFFFFF",
            "surfaceAlt": "EEF2F8",
            "primary": "12305C",
            "primarySoft": "D9E3F2",
            "accent": "C9A227",
            "accentSoft": "F6EFCF",
            "text": "1A2436",
            "muted": "6B7789",
            "line": "CFD8E6",
            "onPrimary": "FFFFFF",
            "onAccent": "2F2705",
        },
        {"heading": CN_SERIF, "body": CN_SANS, "micro": CN_SANS, "headingWeight": "bold"},
        "corner-fold",
        "outline",
        "number",
        {
            "cover": "cover-centered",
            "agenda": "agenda-index",
            "section": "section-side",
            "content": ["content-columns", "content-lead"],
            "cards": ["cards-grid"],
            "case": ["case-brief"],
            "activity": ["activity-cards"],
            "quote": ["quote-left"],
            "metrics": ["metrics-grid"],
            "summary": ["summary-board"],
            "ending": ["ending-cta"],
            "chart": ["chart-full"],
            "table": ["table-full"],
            "timeline": ["timeline-vertical"],
            "process": ["process-steps"],
            "compare": ["compare-table"],
        },
        radius={"card": 0.04, "button": 0.08, "image": 0.03},
        type_scale={"cover": 44, "section": 36, "head": 28, "sub": 18, "body": 15, "micro": 10, "metric": 38, "quote": 26},
    ),
    # ---------------------------------------------------------------- 19
    tpl(
        "lab-science",
        "实验科学",
        "academic",
        "实验照片位、坐标轴网格与公式块，适合物理、化学、生物实验课。",
        ["物理实验", "化学实验", "生物实验", "探究课"],
        {
            "background": "FFFFFF",
            "surface": "FFFFFF",
            "surfaceAlt": "EDF5F3",
            "primary": "0F7B6C",
            "primarySoft": "D6EDE8",
            "accent": "E4572E",
            "accentSoft": "FBE1D8",
            "text": "1C2B2A",
            "muted": "6B7C7A",
            "line": "C9DED9",
            "onPrimary": "FFFFFF",
            "onAccent": "FFFFFF",
        },
        {"heading": CN_HEI, "body": CN_SANS, "micro": CN_SANS, "headingWeight": "bold"},
        "blueprint",
        "outline",
        "rule",
        {
            "cover": "cover-split",
            "agenda": "agenda-list",
            "section": "section-number",
            "content": ["content-sidebar", "content-stack"],
            "cards": ["cards-grid"],
            "case": ["case-brief"],
            "activity": ["activity-steps"],
            "quote": ["quote-left"],
            "metrics": ["metrics-row"],
            "summary": ["summary-map"],
            "ending": ["ending-center"],
            "chart": ["chart-full"],
            "table": ["table-split"],
            "timeline": ["timeline-axis"],
            "process": ["process-steps"],
            "compare": ["compare-columns"],
        },
        radius={"card": 0.05, "button": 0.14, "image": 0.04},
        type_scale={"cover": 42, "section": 36, "head": 28, "sub": 18, "body": 15, "micro": 10, "metric": 38, "quote": 26},
    ),
    # ---------------------------------------------------------------- 20
    tpl(
        "ai-agent",
        "AI 智能体",
        "tech",
        "深色底、神经网络节点与粒子光效，流程与智能体编排页表现最强（TeachNova 品牌模板）。",
        ["AI 通识", "智能体课程", "编程课", "科技竞赛"],
        {
            "background": "0A0F1E",
            "surface": "111A2E",
            "surfaceAlt": "182342",
            "primary": "6C5CE7",
            "primarySoft": "231F4D",
            "accent": "00D2FF",
            "accentSoft": "0C3746",
            "text": "EAF0FF",
            "muted": "7F8CB0",
            "line": "222E4D",
            "onPrimary": "FFFFFF",
            "onAccent": "04222B",
        },
        {"heading": CN_SANS, "body": CN_SANS, "micro": CN_SANS, "headingWeight": "bold"},
        "glow-grid",
        "glass",
        "bar",
        {
            "cover": "cover-fullbleed",
            "agenda": "agenda-grid",
            "section": "section-full",
            "content": ["content-stack", "content-columns"],
            "cards": ["cards-mosaic"],
            "case": ["case-card"],
            "activity": ["activity-cards"],
            "quote": ["quote-centered"],
            "metrics": ["metrics-grid"],
            "summary": ["summary-board"],
            "ending": ["ending-cta"],
            "chart": ["chart-metric"],
            "table": ["table-split"],
            "timeline": ["timeline-rail"],
            "process": ["process-cycle", "process-chevron"],
            "compare": ["compare-split"],
        },
        radius={"card": 0.1, "button": 0.24, "image": 0.08},
        shadow={"enabled": True, "opacity": 0.2, "offset": 3, "blur": 14, "color": "4B3CE0"},
        type_scale={"cover": 46, "section": 38, "head": 30, "sub": 18, "body": 15, "micro": 10, "metric": 44, "quote": 28},
        chart_style={"mode": "dark"},
        dark=True,
        footer="TeachNova · AI 互动式教学智能体",
    ),
]


def main() -> None:
    TPL_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for item in TEMPLATES:
        folder = TPL_DIR / item["id"]
        folder.mkdir(parents=True, exist_ok=True)
        (folder / "template.json").write_text(
            json.dumps(item, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )
        written.append(item["id"])
    print(f"wrote {len(written)} templates: {', '.join(written)}")


if __name__ == "__main__":
    main()
